services:
  postgres:
    image: postgres:16.3-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
